const tips = [
  {
    id: 1,
    category: 'Buying Guide',
    readTime: '4 min read',
    title: 'How to Choose the Right Fridge Size for Your Family',
    excerpt:
      "Our AI analyzed 50,000 households and found that families of 4–5 need at least 500L. Here's the complete sizing formula — including pantry habits, climate, and shopping frequency.",
    image: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=700&h=420&fit=crop&auto=format',
    tags: ['Refrigerators', 'Family Guide', 'AI Insight'],
    date: 'Sep 3, 2024',
    author: 'CoolHome AI',
  },
  {
    id: 2,
    category: 'Energy Savings',
    readTime: '3 min read',
    title: 'Inverter vs. Fixed-Speed AC: The Real Cost Over 5 Years',
    excerpt:
      'We ran the numbers. An inverter AC saves an average of $218/year vs. fixed-speed. Over 5 years, that offsets up to 65% of the purchase price — even for premium models.',
    image: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=700&h=420&fit=crop&auto=format',
    tags: ['Air Conditioners', 'Energy', 'Cost Analysis'],
    date: 'Aug 28, 2024',
    author: 'CoolHome AI',
  },
  {
    id: 3,
    category: 'Smart Home Tips',
    readTime: '5 min read',
    title: 'Connect All Your Appliances: SmartThings vs. ThinQ vs. Home Connect',
    excerpt:
      'Samsung, LG, and Bosch each have their own smart home ecosystem. We tested all three for 30 days to tell you which integrates best with Alexa, Google Home, and Apple HomeKit.',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=700&h=420&fit=crop&auto=format',
    tags: ['Smart Home', 'Comparison', 'AI Review'],
    date: 'Aug 20, 2024',
    author: 'CoolHome AI',
  },
]

function AiChip() {
  return (
    <span className="inline-flex items-center gap-1.5 bg-brand-light border border-brand-light text-brand text-xs font-semibold font-display px-2.5 py-1 rounded-full">
      <svg viewBox="0 0 16 16" className="w-3.5 h-3.5" fill="none">
        <path d="M8 1.5l1 3h3l-2.4 1.8.9 2.7-2.5-1.8-2.5 1.8.9-2.7L3 4.5h3z" fill="#1D4ED8" />
        <circle cx="13" cy="3" r="1.2" fill="#60A5FA" />
        <circle cx="3" cy="12" r="0.8" fill="#93C5FD" />
      </svg>
      AI Generated
    </span>
  )
}

export default function AiBlog() {
  return (
    <section className="py-16 bg-brand-pale border-t border-brand-light">
      <div className="max-w-7xl mx-auto px-4 sm:px-8 lg:px-12">
        <div className="flex items-end justify-between mb-10">
          <div>
            <p className="text-brand text-sm font-semibold font-display uppercase tracking-widest mb-1">Powered by AI</p>
            <h2 className="text-3xl font-display font-bold text-gray-900">Tips & Buying Guides</h2>
            <p className="text-gray-500 font-body mt-2 text-sm">Expert insights generated by CoolHome AI — updated weekly</p>
          </div>
          <a href="#" className="text-sm text-brand font-medium hover:underline font-body hidden sm:block">
            View all articles →
          </a>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          {tips.map((tip) => (
            <article
              key={tip.id}
              className="group bg-white rounded-2xl overflow-hidden border border-gray-100 hover:border-brand-light hover:shadow-xl hover:shadow-blue-50 transition-all duration-300 flex flex-col"
            >
              <div className="relative overflow-hidden bg-brand-light aspect-[16/9]">
                <img
                  src={tip.image}
                  alt={tip.title}
                  className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-500"
                />
                <div className="absolute inset-0 bg-gradient-to-t from-black/30 to-transparent" />
                <div className="absolute top-3 left-3">
                  <span className="text-xs font-semibold font-display bg-white/95 backdrop-blur-sm text-brand px-2.5 py-1 rounded-full">
                    {tip.category}
                  </span>
                </div>
              </div>

              <div className="flex flex-col flex-1 p-5 gap-3">
                <div className="flex items-center gap-2">
                  <AiChip />
                  <span className="text-xs text-gray-400 font-body">{tip.readTime}</span>
                </div>

                <h3 className="text-base font-bold font-display text-gray-900 leading-snug group-hover:text-brand transition-colors">
                  {tip.title}
                </h3>

                <p className="text-sm text-gray-500 font-body leading-relaxed flex-1 line-clamp-3">
                  {tip.excerpt}
                </p>

                <div className="flex flex-wrap gap-1.5">
                  {tip.tags.map(tag => (
                    <span key={tag} className="text-xs bg-brand-pale text-brand-dark px-2 py-0.5 rounded-full font-body">
                      {tag}
                    </span>
                  ))}
                </div>

                <div className="flex items-center justify-between pt-3 border-t border-gray-100">
                  <div className="flex items-center gap-2">
                    <div className="w-6 h-6 bg-brand rounded-full flex items-center justify-center">
                      <svg viewBox="0 0 16 16" className="w-3.5 h-3.5" fill="white">
                        <path d="M8 1.5l1 3h3l-2.4 1.8.9 3-2.5-1.8-2.5 1.8.9-3L3 4.5h3z" />
                      </svg>
                    </div>
                    <span className="text-xs text-gray-500 font-body">{tip.author}</span>
                  </div>
                  <span className="text-xs text-gray-400 font-body">{tip.date}</span>
                </div>
              </div>
            </article>
          ))}
        </div>

        <div className="mt-10 bg-gradient-to-r from-brand-dark to-brand rounded-2xl p-6 sm:p-8 flex flex-col sm:flex-row items-center gap-6">
          <div className="flex-shrink-0 w-14 h-14 bg-white/10 rounded-2xl flex items-center justify-center">
            <svg viewBox="0 0 32 32" className="w-8 h-8" fill="none">
              <path d="M16 4l2 7h7l-5.7 4.1 2.2 6.9L16 18.2l-5.5 3.8 2.2-6.9L7 11h7z" fill="#FCD34D" />
              <circle cx="26" cy="7" r="2.5" fill="#60A5FA" />
              <circle cx="5" cy="24" r="1.5" fill="#93C5FD" opacity="0.7" />
            </svg>
          </div>
          <div className="flex-1 text-center sm:text-left">
            <h3 className="text-xl font-display font-bold text-white mb-1">
              Ask our AI — get personalized buying advice
            </h3>
            <p className="text-blue-200 font-body text-sm">
              Tell us your budget, room size, and family needs. Our AI recommends the perfect appliance in seconds.
            </p>
          </div>
          <button className="flex-shrink-0 bg-white text-brand-dark px-6 py-3 rounded-xl font-display font-semibold hover:bg-brand-light transition-colors active:scale-95 whitespace-nowrap">
            ✨ Try AI Advisor
          </button>
        </div>
      </div>
    </section>
  )
}
